### PR TITLE
Added norwegian translation

### PR DESCRIPTION
**Pull request by kimfy**

### CODE REVIEW

**Comment by kennedyoliveira** [comment]
Thank you very much for the contribution @kimfy !

**Comment by kennedyoliveira** [comment]
@kimfy, i updated the plugin, could you please test and check if the different symbols are showing correct? Thank you again

**Comment by kimfy** [comment]
Special characters are not showing up properly. ÆæØøÅå are the special ones, I'd look into it but unfortunately have no time at the moment.

**Comment by kennedyoliveira** [comment]
@kimfy thanks for the feedback, i 'll fix it today

**Comment by kennedyoliveira** [comment]
@kimfy, i fixed the special characters and tried in my computer and it's working fine, could you please test and give me a feedback?

**Comment by kimfy** [comment]
Yep I'll check!

**Comment by kennedyoliveira** [comment]
Your welcome, @kimfy! I'm glad it worked now!
And thanks again for translating the plugin!
If you think in something that could be improved in the plugin, feel free to open issues for enhancements, every feedback are welcome!
cya!

**Comment by kimfy** [comment]
No worries, I'll be using it a lot so I'm sure I'll be back here, hah! ✊

**Review by ronaldinzkie — COMMENTED** [review]
src/com/github/kennedyoliveira/ultimatepastebin/i18n/MessageBundle.java

**Pull request merged**
